=== eleven5150/mips-emulation/benchmarking/pipeline/pipeline.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "BencherPipeline",
  "description": "Pipeline definition for Bencher",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "description": "Schema reference"
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "test": {
      "type": "string",
      "enum": [
        "full",
        "hello_world",
        "versions",
        "local",
        "matmul",
        "prime_number",
        "qsort"
      ]
    },
    "pipeline": {
      "$ref": "#/definitions/Pipeline"
    }
  },
  "required": [
    "name",
    "description",
    "pipeline",
    "test"
  ],
  "additionalProperties": false,
  "definitions": {
    "Pipeline": {
      "type": "object",
      "description": "Pipeline stages",
      "items": {
        "$ref": "#/definitions/PipelineItem"
      }
    },
    "PipelineItem": {
      "type": "object",
      "description": "Language with tests",
      "items": {
        "type": "array"
      }
    }
  }
}

=== eleven5150/mips-emulation/benchmarking/pipeline/pipeline-prime-number.json
{
  "$schema": "pipeline.schema.json",
  "name": "Prime number",
  "description": "Pipeline with calculating prime numbers tests",
  "test": "prime_number",
  "pipeline": {
    "c": [
      "prime_number"
    ],
    "c#": [
      "prime_number"
    ],
    "cython": [
      "prime_number"
    ],
    "javascript": [
      "prime_number"
    ],
    "kotlin_jvm": [
      "prime_number"
    ],
    "python": [
      "prime_number"
    ],
    "rust": [
      "prime_number"
    ]
  }
}

=== eleven5150/mips-emulation/bencher/pipeline/pipeline-qsort.json
{
  "$schema": "pipeline.schema.json",
  "name": "Quick sort",
  "description": "Pipeline with quick sort tests",
  "test": "qsort",
  "pipeline": {
    "c": [
      "qsort"
    ],
    "c#": [
      "qsort"
    ],
    "cython": [
      "qsort"
    ],
    "javascript": [
      "qsort"
    ],
    "kotlin_jvm": [
      "qsort"
    ],
    "python": [
      "qsort"
    ],
    "rust": [
      "qsort"
    ]
  }
}

=== eleven5150/mips-emulation/benchmarking/pipeline/pipeline-matmul.json
{
  "$schema": "pipeline.schema.json",
  "name": "Matrix multiplication",
  "description": "Pipeline with matrix multiplication tests",
  "test": "matmul",
  "pipeline": {
    "c": [
      "matmul"
    ],
    "c#": [
      "matmul"
    ],
    "cython": [
      "matmul"
    ],
    "javascript": [
      "matmul"
    ],
    "kotlin_jvm": [
      "matmul"
    ],
    "python": [
      "matmul"
    ],
    "rust": [
      "matmul"
    ]
  }
}

=== eleven5150/mips-emulation/bencher/pipeline/pipeline-versions.json
{
  "$schema": "pipeline.schema.json",
  "name": "Versions",
  "description": "Pipeline with printing languages versions",
  "test": "versions",
  "pipeline": {
    "c": [
      "version"
    ],
    "c#": [
      "version"
    ],
    "cython": [
      "version"
    ],
    "javascript": [
      "version"
    ],
    "kotlin_jvm": [
      "version"
    ],
    "kotlin_native": [
      "version"
    ],
    "python": [
      "version"
    ],
    "rust": [
      "version"
    ]
  }
}
